### ISSUE TITLE
test/conftest.py is missing from sdist

### ISSUE THREAD

**Issue by viccuad** [neovim/pynvim#348]
Hello,

While packaging a new Debian release, I found that `test/conftest.py` doesn't get included
in the sdist (which breaks the tests as fixtures are missing).

It puzzles me a bit, since AFAIK `python.py sdist` will include all `*.py`.

Cheers.

**Comment by bfredl** [comment]
It was a time ago we made a release, I plan to do one the following days and will check this then.

**Comment by justinmk** [comment]
Release was published.
