### ISSUE TITLE
Get logging/output from rplugin in tests

### ISSUE THREAD

**Issue by blueyed** [neovim/pynvim#349]
I would like to get to an rplugin's logging output during tests.

I am using a `nvim` fixture similar to what neovim-python-client uses in its own tests (https://github.com/Shougo/deoplete.nvim/pull/807/files#diff-f57b4d3a4403d70b647003618269deeaR35).

The rplugin is deoplete, where I have tried to setup the logging to output to stderr.

Is it possible to get the rplugin's stderr/logging into the test process easily?

**Comment by justinmk** [comment]
Not yet, but something like this is discussed in core neovim repo.
