### ISSUE TITLE
Deprecated import

### ISSUE THREAD

**Issue by daniele-orlando** [neovim/pynvim#351]
System: MacOS
Neovim: **0.3.0**
Python: **3.7**
Python client (neovim): **0.2.6**

> DeprecationWarning: the **imp** module is deprecated in favour of **importlib**; see the module's documentation for alternative uses

It is triggered by the plugin `vim-visual-multi` when using the `python3` api.

**Comment by justinmk** [comment]
https://github.com/neovim/pynvim/pull/461
