### ISSUE TITLE
test/conftest.py missing from pypi package

### ISSUE THREAD

**Issue by medvid** [neovim/pynvim#367]
pynvim-0.3.1.tar.gz as available at https://pypi.org/project/pynvim/#files, doesn't match the github tarball (https://github.com/neovim/pynvim/archive/0.3.1.tar.gz) - test/conftest.py is missing.

As a result, all tests are failing (fixture 'vim' not found).

For some reason python setup.py sdist doesn't include test/conftest.py in the distribution tarball. This is the same issue as #348, which was not fixed in 0.3.1.

**Comment by bfredl** [comment]
Not sure how to fix this, nothing in our config is subsetting the files in `test/` subdir. Should one extract the `sdist` generated tarball, add the missing file, and recompress it, and hope than nothing else breaks?

**Comment by 0mp** [comment]
I've stumbled upon the same problem.
