### ISSUE TITLE
Relationship to neovim module

### ISSUE THREAD

**Issue by goerz** [neovim/pynvim#378]
What is the relationship between this project and the `neovim` Python package that the [Neovim documentation talks about](https://github.com/neovim/neovim/wiki/FAQ#python-support-isnt-working)?

**Comment by goerz** [comment]
Ah, I found this: https://github.com/neovim/neovim/wiki/Following-HEAD#20181118

So this isn't released yet? I think I'm currently running Neovim `v0.2.3-dev` on my Mac, so I should stick to the `neovim` module for now? It would probably a good idea to put a notice into the README of `pynvim` explaining that this is the successor to the `neovim` module, and when one should install `pynvim` or `neovim` -- and update the Neovim documentation.

**Comment by justinmk** [comment]
The FAQ needed an update (done).

> So this isn't released yet?

`pynvim` was released.

> so I should stick to the neovim module for now?

No.

>  when one should install pynvim or neovim -- and update the Neovim documentation.

`neovim` pip module/package is simply a wrapper around `pynvim`. All documentation has been updated AFAIK, now that the FAQ was just updated.

**Comment by goerz** [comment]
Sounds good! I'd still mention both here in the README and in the FAQ that the package used to be called `neovim`. I think a lot of people are going to be confused when they come across references to the old `neovim` package on the web (or even just when upgrading their installation)
