### ISSUE TITLE
PendingDeprecationWarning: encoding is deprecated in msgpack_stream.py:24

### ISSUE THREAD

**Issue by mcepl** [neovim/pynvim#379]
When running a test suite for https://github.com/mhinz/neovim-remote/ I get plenty of warnings:
```
/usr/lib/python3.6/site-packages/pynvim/msgpack_rpc/msgpack_stream.py:24: \
    PendingDeprecationWarning: encoding is deprecated.
    unicode_errors=unicode_errors_default)
```

**Comment by mhinz** [comment]
This is fixed on master: https://github.com/neovim/pynvim/commit/c771bfd4c13683096d10432376a9dedb4aef66b2

@bfredl @justinmk Time for 0.3.2?

**Comment by bfredl** [comment]
Sure, I'll do it.

**Comment by bfredl** [comment]
Released.
