### ISSUE TITLE
Updating neovim package breaks deoplete on both CentOS and Windows.

### ISSUE THREAD

**Issue by jdhao** [neovim/pynvim#380]
I have found that updating neovim package from 0.2.6 to 0.3.1 breaks deoplete on both CentOS and Windows.  The cause is that when upgrading to 0.3.1, Neovim python package is actually not installed, only the wheel info is present. 

My environment is as follows:

+ Platform: CentOS  7 and Windows 10 (This issue occurs on both Platforms)
+ Neovim: 0.3.2
+ Python: 3.6.5 (provided by Anaconda)

I have also written a very detailed description [here](https://github.com/neovim/neovim/issues/8085#issuecomment-453497235).

**Comment by justinmk** [comment]
Did you see https://github.com/neovim/neovim/wiki/Following-HEAD#20181118 ? Try this:

```
pip uninstall neovim pynvim
pip install pynvim
```

**Comment by jdhao** [comment]
Sorry, I am not aware of that. When I install this package back in September 2018, it is still named `neovim`.

**Comment by justinmk** [comment]
The next maintenance release (0.3.4) should avoid this issue for other users, since it will include https://github.com/neovim/neovim/pull/9468
