### ISSUE TITLE
Is there anyway to auto-complete the nvim object?

### ISSUE THREAD

**Issue by DenLilleMand** [neovim/pynvim#382]
I am following your documentation, and i found the online docs of the nvim commands. But is it possible to auto-complete these?

Sorry for being clueless, i am not that confident in python. But i guess it is more of a question about how to get auto-complete on python objects where you don't really know it's type before hand.

I am using deoplete-jedi which works fine for the `pynvim` module it self.

**Comment by blueyed** [comment]
Jedi supports type annotations.  See https://docs.python.org/3/library/typing.html.

This should be closed since it's not a pynvim issue.

Feel free to follow up though, providing some example code.
