### ISSUE TITLE
icons from NerdFonts throw cursor reading off

### ISSUE THREAD

**Issue by ipsod** [neovim/pynvim#383]
This isn't a NerdFont icon, but I'm going to use it for the example: `»`.

On a line like this:

»t

With cursor on `t`, `nvim.current.window.cursor[1]` returns `3`, when it should return `1`.

**Comment by justinmk** [comment]
> it should return `1`

Based on what? The cursor is on byte 3. » is a multibyte character. Buffer lines/columns in the legacy if_pyth interface are 1-indexed.

**Comment by bfredl** [comment]
In my testing it returns returns 2. Which is what I would expect: 0-indexed bytes. This is consistent between vim and pynvim.

**Comment by ipsod** [comment]
Ah, I'm not used to having to bother with strings vs. bytes, I assumed a 1:1 correlation between displayed characters and column, as I was thinking of columns as visual things, which still makes more sense to me, but maybe I don't know enough to know the reasoning.  The character in particular I'm testing seems to have 3 bytes: `\xef\xad\x82`.  My version of pynvim and python do seem to have column as 0-indexed, though, and not 1-indexed.

**Comment by justinmk** [comment]
> seem to have column as 0-indexed, though, and not 1-indexed.

Yes, that was my wrong assumption. Although it is still true that the editor/legacy generally speaks of "column 1", never "column 0".

The Nvim API is consistently 0-indexed except for legacy features, AFAIK.

**Comment by bfredl** [comment]
if_python "legacy" at least to some extent follows python convention of zero-indexing. `vim.current.window.cursor` has one-indexed lines and zero-indexed columns, I suppose just because.

> Since Python 3 uses strings by default, leaving most users to never worry about bytes, it might be worth noting in the pynvim documentation? I think it will surprise many people, otherwise.

@ipsod Characters (which I assume you mean by "strings" as opposed to bytes) is by definition a non-trivial concept in Unicode. Python 3.3+ `str` uses codeunits, but this is still not the same thing as user-editable characters (by vim and most other editors). The closest somewhat well-defined thing to that are  graphemes (or "composed chars" as vim calls them), and these differ by Unicode version.

**Comment by ipsod** [comment]
The problem I have with this, is that, if I run:

    col = nvim.current.buffer[nvim.current.window.cursor[0]].find("string")]
    nvim.current.window.cursor = [nvim.current.window.cursor[0], col]

the position of the cursor is moved, if any of the characters preceding `col` are multi-byte characters.  I can work with this, of course, with a little extra code, but it seems both inconvenient and surprising.

**Comment by bfredl** [comment]
The interface does allow to switch to a bytes mode by using `nvim = nvim.with_decode(False)`. Then buffer text and so forth will be represented by the bytes that vim use directly.

**Comment by ipsod** [comment]
That doesn't seem to change the functioning of that bit of code I included above - it still moves the cursor.

**Comment by ipsod** [comment]
Using that causes the code above to fail: `TypeError: argument should be integer or bytes-like object, not 'str'`.  So, it's just swapping which end the plugin-developer has to do type-conversions on.
