### ISSUE TITLE
:checkhealth shows Python3 Provider `unable to load neovim Python Module` - typical solutions not working

### ISSUE THREAD

**Issue by komali2** [neovim/pynvim#388]
Healthcheck fails. Python3 can't find  neovim Python3 module. Python 2 provider can. 

Scroll to bottom for attempts at solving based on googling, stackoverflowing, and searching this repo's issues. 

**Expected result of `checkhealth`** : All passed

System information: 

**lsb_release -a**

```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```
**nvim --version**

```
NVIM v0.3.4
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/caleb/Downloads/neovim-0.3.4/build/config -I/home/caleb/Downloads/neovim-0.3.4/src -I/home/caleb/Downloads/neovim-0.3.4/.deps/usr/include -I/usr/include -I/home/caleb/Downloads/neovim-0.3.4/build/src/nvim/auto -I/home/caleb/Downloads/neovim-0.3.4/build/include
Compiled by caleb@caleb-Potatop

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info

```

**:checkhealth**

```
health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $VTE_VERSION='5202'
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - INFO: Using: g:python_host_prog = "/home/caleb/.cache/vim/venv/neovim2/bin/python"
  - INFO: Executable: /home/caleb/.cache/vim/venv/neovim2/bin/python
  - INFO: Python version: 2.7.15
  - INFO: pynvim version: 0.3.2
  - OK: Latest pynvim is installed.

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/home/caleb/.cache/vim/venv/neovim3/bin/python3"
  - INFO: Executable: /home/caleb/.cache/vim/venv/neovim3/bin/python3
  - ERROR: Command error (job=9, exit code 1): `'/home/caleb/.cache/vim/venv/neovim3/bin/python3' -c 'import sys; sys.path.remove(""); import neovim; print(neovim.__file__)'` (in '/home/caleb/.cache/vim/venv/neovim3/bin')
    Output: Traceback (most recent call last):  File "<string>", line 1, in <module>ModuleNotFoundError: No module named 'neovim'
    Stderr: Traceback (most recent call last):  File "<string>", line 1, in <module>ModuleNotFoundError: No module named 'neovim'
  - INFO: Python version: 3.6.7
  - INFO: pynvim version: unable to load neovim Python module
  - ERROR: pynvim is not installed.
    Error: unable to load neovim Python module
    - ADVICE:
      - Run in shell: pip3 install pynvim

## Ruby provider (optional)
  - INFO: Disabled. g:loaded_ruby_provider=1

## Node.js provider (optional)
  - INFO: Node.js: v11.10.1
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim

```

**Attempts to Solve**:

```
pip3 uninstall neovim
pip3 uninstall pynvim
pip3 install pynvim
```

```
pip2 uninstall neovim
pip2 uninstall pynvim
pip2 install pynvim
```

```
pip uninstall neovim
pip uninstall pynvim
pip install pynvim
```

No other `pip` is installed on this system.

I suspect this has something to do with the large number of `python` runtimes installed on this system, though I've pointed `g:python_host_prog` all over the place to no joy. 

**python[tab]**

```
python             python2.7          python2-config     python3.6          python3.6m         python3-config     python3m-config    
python2            python2.7-config   python3            python3.6-config   python3.6m-config  python3m           python-config  
```

**Comment by justinmk** [comment]
`g:python3_host_prog` points to a venv, but it's not clear which commands were executed in the context of the venv. E.g. when you say `pip3 uninstall neovim`, is that with the venv activated? Alternatively:

   /home/caleb/.cache/vim/venv/neovim3/bin/pip3 uninstall neovim
   /home/caleb/.cache/vim/venv/neovim3/bin/pip3 uninstall pynvim
   /home/caleb/.cache/vim/venv/neovim3/bin/pip3 install pynvim

**Comment by komali2** [comment]
Oh, good idea. Hmm, `/home/caleb/.cache/vim/venv/neovim3/bin/pip` is a directory, lemme get to hunting down pip though

**Comment by komali2** [comment]
Further news: neovim2 seems to have the actual pip binaries... and it has many. `pip pip2 pip2.7`

**Comment by komali2** [comment]
pip, pip2, pip2.7 inside neovim2/bin uninstall of neovim and pynvim, then reinstallation of pynvim, did not solve the issue, though we could have predicted that. Trying to see why pip is a directory and not an executable inside neovim3/bin now.

**Comment by komali2** [comment]
In a real shoot from the hip attempt, I `cp`'d the `neovim2/bin` version of pip into `neovim3/bin` and ran the uninstall/install commands. No joy.

**Comment by justinmk** [comment]
> Trying to see why pip is a directory and not an executable inside neovim3/bin now.

Indeed. Well, I think the recommended way to invoke pip is now `python -m pip`. So that's probably why python3 doesn't have the aliases. Try this:

```
/home/caleb/.cache/vim/venv/neovim3/bin/python -m pip uninstall neovim
/home/caleb/.cache/vim/venv/neovim3/bin/python -m pip uninstall pynvim
/home/caleb/.cache/vim/venv/neovim3/bin/python -m pip install pynvim
```

Anyways, this is a virtualenv matter.

**Comment by komali2** [comment]
I couldn't do `bin/python -m pip` because the pip module wasn't installed for uh, these pythons in here. Not sure. Anyway this solved it. 

`cd /home/caleb/.cache/vim/venv/neovim3/bin/`

Use the get-pip script from this directory: 

`curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py`

`./python3 get-pip.py`

`./python3 -m pip uninstall neovim`

`./python3 -m pip uninstall pynvim`

`./python3 -m pip install pynvim`

It's messy, but it works now. Cheers for the help.

**Comment by justinmk** [comment]
In your steps I never see any "activate" step. So I would think that `./python3` is going to find and use the system python. I would figure out why pip isn't in your virtualenv, or else don't bother using a virtualenv...
