### ISSUE TITLE
`buf1 != buf2` doesn't work in python2

### ISSUE THREAD

**Issue by Yggdroot** [neovim/pynvim#398]
- `nvim --version`: NVIM v0.4.0-758-g9e0982a1a
- Vim (version: ) behaves differently? yes
- Operating system/version: Linux
- Terminal name/version:
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```
Suppose there is a file bug.vim:

```python
py << EOF
import vim

aaa = vim.current.buffer
print(aaa == vim.current.buffer, aaa != vim.current.buffer)

EOF
```
Source the file: `so %`

This bug only happen when using python2, It works well for python3.
### Actual behaviour

Result is (True, True) .

### Expected behaviour

Result is (True, False) .

**Comment by noelevans** [comment]
I have a fix for this. It passes for both python 2.7 and 3.7. 

Adding the unit test, I also fixed a warning on test_buffer.py:96. Previously the module printed the warning below when run with python 3.7:
/home/noel/repo/pynvim/test/test_buffer.py:96: DeprecationWarning: invalid escape sequence \s
    assert vim.options['define'] == '^\s*#\s*define'

I'm sending the pull request now
