### ISSUE TITLE
can not import unpackb from msgpack

### ISSUE THREAD

**Issue by jdhao** [neovim/pynvim#401]
I got this error on Windows suddenly when I open nvim-qt. This error occurs both for Neovim nightly version and stable release.

Previously, there is no such error. I am not sure why it happens suddenly. I solved the issue by uninstalling `msgpack` and reinstall it.

```
pip uninstall msgpack
pip install msgpack
```

**Comment by bfredl** [comment]
Sounds like it was an issue about `msgpack` package then. I'm not sure what we can do about it.
