### ISSUE TITLE
Unable to feed multiple keys at once 

### ISSUE THREAD

**Issue by iamsimha** [neovim/pynvim#415]
I am trying to feed multiple keystrokes at once via the nvim.feedkeys and nvim.input  functions.

Example: 
1. CTRL - [  (For exiting the insert mode)
2. CTRL-d  (for moving the cursor to the end of screen)
``` python
nvim = attach('socket', path='/tmp/nvim.socket')
nvim.input("\<c-l>d") # This does not work as expected. The cursor doesnot move to the end of screen
```
Basically the input api does not allow a key hold event. Instead it process the keypress greedily.

**Comment by iamsimha** [comment]
Sorry, My bad I was able to do this using 
```
nvim.replace_termcodes("<c-[>")
```

**Comment by justinmk** [comment]
>     nvim.input("\<c-l>d")

Just remove the backslash.
