### ISSUE TITLE
Extra unused dependency?

### ISSUE THREAD

**Issue by vext01** [neovim/pynvim#417]
Hi,

In setup.py, we have:
```
setup_requires = [
    'pytest-runner'
]
```

However, I don't think it's actually used. If you remove this dependency, the package will build and test without issue.

Kill it?

**Comment by bfredl** [comment]
https://pypi.org/project/pytest-runner/  seems to indicate that `tox` which we already use on CI replaces pytest-runner. So probably safe to delete.

**Comment by blueyed** [comment]
@vext01 
Good find!
Will you create a PR for it?
Check https://github.com/pytest-dev/pytest-runner#deprecation-notice.
