### ISSUE TITLE
unresolved dependency pytest-runner on python 37 install

### ISSUE THREAD

**Issue by Warpulis** [neovim/pynvim#420]
I'm on a new python 3.7.4 on Windows 10 and tried to

    C:\Python37\python.exe -m pip install --proxy "<removed>" pynvim

The process hangs  and after Ctrl-C I got an error message about the missing dependency 

    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest-runner')

After
     
    C:\Python37\python.exe -m pip install --proxy "<removed>" pytest-runner

pynvim installs just fine.

P.S.: Full log output:

>    ERROR: Command errored out with exit status 1:
>      command: 'C:\Python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"[Userhome]\\AppData\\Local\\Temp\\pip-install-d7kgpoi9\\pynvim\\setup.py'"'"'; __file__='"'""[Userhome]\\AppData\\Local\\Temp\\pip-install-d7kgpoi9\\pynvim\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base ‘"[Userhome]\AppData\Local\Temp\pip-install-d7kgpoi9\pynvim\pip-egg-info'
>          cwd: "[Userhome]\AppData\Local\Temp\pip-install-d7kgpoi9\pynvim\
>     Complete output (25 lines):
>     Download error on https://pypi.org/simple/pytest-runner/: timed out -- Some packages may not be found!
>     Couldn't find index page for 'pytest-runner' (maybe misspelled?)
>     Download error on https://pypi.org/simple/: timed out -- Some packages may not be found!
>     No local packages or working download links found for pytest-runner
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File ""[Userhome]\AppData\Local\Temp\pip-install-d7kgpoi9\pynvim\setup.py", line 50, in <module>
>         zip_safe=False)
>       File "C:\Python37\lib\site-packages\setuptools\__init__.py", line 144, in setup
>         _install_setup_requires(attrs)
>       File "C:\Python37\lib\site-packages\setuptools\__init__.py", line 139, in _install_setup_requires
>         dist.fetch_build_eggs(dist.setup_requires)
>       File "C:\Python37\lib\site-packages\setuptools\dist.py", line 724, in fetch_build_eggs
>         replace_conflicting=True,
>       File "C:\Python37\lib\site-packages\pkg_resources\__init__.py", line 782, in resolve
>         replace_conflicting=replace_conflicting
>       File "C:\Python37\lib\site-packages\pkg_resources\__init__.py", line 1065, in best_match
>         return self.obtain(req, installer)
>       File "C:\Python37\lib\site-packages\pkg_resources\__init__.py", line 1077, in obtain
>         return installer(requirement)
>       File "C:\Python37\lib\site-packages\setuptools\dist.py", line 791, in fetch_build_egg
>         return cmd.easy_install(req)
>       File "C:\Python37\lib\site-packages\setuptools\command\easy_install.py", line 673, in easy_install
>         raise DistutilsError(msg)
>     distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest-runner')
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by justinmk** [comment]
should be fixed by https://github.com/neovim/pynvim/pull/418 but I'm thinking we should remove it entirely.
