### ISSUE TITLE
Drop support for Python 2 and 3.4 (type annotations)?

### ISSUE THREAD

**Issue by blueyed** [neovim/pynvim#422]
I'm looking into adding type annotations, and would like to do this for Python 3.5+ then.

Both Python 2 and 3.4 are EOL by now, and it might take time anyway to merge type annotations then anyway.

What do you think?

**Comment by bfredl** [comment]
Dropping support for python 2 on master is fine. We could create a separate maintenance branch for bug-fixes only on top of 0.4.0 (or whatever the last python 2 version)

**Comment by blueyed** [comment]
Ok, what about Python 3.4?

**Comment by bfredl** [comment]
Same thing there, python 3.4 can stay on 0.4.0/maintenance branch (if anyone still uses it). Lets move master forward.

**Comment by blueyed** [comment]
Cool.  No need to do this already, but good to know how to proceed in this regard.

**Comment by noelevans** [comment]
Would you be able to accept help doing this if it were to be delivered module-by-module? If so is there any particular order to follow?

**Comment by blueyed** [comment]
@noelevans 
I think "removing support" is not a goal, but should be done when it gets into the way somewhere.
Then it is as easy as removing the classifiers and CI config, so it's not really a task by itself.

**Comment by farisachugthai** [comment]
Alternatively, if python2 support is desirable so as to not phase out support for entirely for type annotations, `typing` is a pip installable library on python<3.5.

https://mypy.readthedocs.io/en/latest/python2.html

So we could add it as an install_requirement in the setup.py `if sys.version < (3,5):`
