### ISSUE TITLE
Release process: document, automate

### ISSUE THREAD

**Issue by blueyed** [neovim/pynvim#428]
For easier releases it would be nice if tags get deployed via Travis.

See https://github.com/Vimjas/vint/blob/db881f8fe7127cd092436371643e48903099f114/.travis.yml#L38-L53 for reference - it uses a token generated via PyPI's admin interface.

**Comment by justinmk** [comment]
IIUC  you're suggesting that when a human creates a tag, that should trigger CI to publish to pypi. 

That could be nice, although it depends on how cumbersome the release process is. I would guess if we just document it [like the lua-client repo](https://github.com/neovim/lua-client#release) that would solve 80% of the friction.

**Comment by blueyed** [comment]
The main benefit here is also to ensure a predictable environment, to not include/upload unwanted files (just happened with pip 20 even (https://github.com/pypa/pip/pull/7624)).

**Comment by bfredl** [comment]
>  to not include/upload unwanted files 

Currently I do this by diffing every release tarball against the last one. But if someone wants to write a nice script, that would be a welcome addition.

**Comment by justinmk** [comment]
@bfredl are the steps to release written down somewhere? I actually have never done it for this repo, thus can't write them myself.

**Comment by bfredl** [comment]
@justinmk Currently only in my zsh_history, but I will write something down (but nothing unexpected, really). But probably we want to _improve_ the process to include the disabling of excessive logging (there is a script somewhere we could revive)

 I think currently I'm the only one having ownership on the `pynvim` pypi package, I could add you to it if you have a pypi account.

**Comment by bfredl** [comment]
I just made a release, and wrote done what I did at the same time:

1. Create a release commit with the title "Pynvim x.y.z"

   - list significant changes in the commit message
   - bump the version in pynvim/util.py and setup.py (3 places in total)

2. Make a release on github with the same commit/version tag and copy the message.

3. run `scripts/disable_log_statements.sh`

4. run `python setup.py sdist`

    - Here I usually diff the release tarball dist/pynvim-x.y.z.tar.gz against the previous one

5. run `twine upload -r pypi dist/pynvim-x.y.z.tar.gz` (assumes you have a pypi account with permissions)

6. run `scripts/enable_log_statements.sh` or `git reset --hard` to restore the working dir

**Comment by justinmk** [comment]
Thanks, documented in https://github.com/neovim/pynvim/pull/429.

That should be enough. I strongly believe we shouldn't spend time automating this. Parts of it can't be automated (e.g. human needs to write the release notes, human needs to authenticate to pypi), and other parts are trivial compared to those tasks.

**Comment by justinmk** [comment]
>  run `twine upload -r pypi dist/pynvim-x.y.z.tar.gz` (assumes you have a pypi account with permissions)

I guess this replaces [publish.sh](https://github.com/neovim/pynvim/blob/master/scripts/publish.sh) ?
