### ISSUE TITLE
Incorrectly set version in setup.py

### ISSUE THREAD

**Issue by mcepl** [neovim/pynvim#431]
You have in ``setup.py`` still ``version = 0.4.0``.

This [patch](https://github.com/neovim/pynvim/files/4236038/setup_version.patch.txt) fixes it, but it is a bit obvious.

**Comment by justinmk** [comment]
? Where are you getting this from? A tarball somewhere? pypi? 

version was set to 0.4.1 in https://github.com/neovim/pynvim/commit/dd45f83c798fcb5bbb5be4a0843f6e0b47e06bd0

**Comment by mcepl** [comment]
> ? Where are you getting this from? A tarball somewhere? pypi?
> 
> version was set to 0.4.1 in [dd45f83](https://github.com/neovim/pynvim/commit/dd45f83c798fcb5bbb5be4a0843f6e0b47e06bd0)

Tarball of course. https://github.com/neovim/pynvim/archive/0.4.1/pynvim-0.4.1.tar.gz

**Comment by justinmk** [comment]
You're right, `0.4.1` tag points to some mistaken commit, and its setup.py is wrong:

https://github.com/neovim/pynvim/blob/0.4.1/setup.py

Hopefully now that release process is [documented](https://github.com/neovim/pynvim#release) this won't happen again. We should release 0.4.2 soon to fix this.
