### ISSUE TITLE
Check the command regist

### ISSUE THREAD

**Issue by yanganto** [neovim/pynvim#437]
Hi, I run to a strange environment,  and I want to debug to know the command registered from a plugin.
How can I do this?
Thanks.

The more detail that I run into is that in this `nvim-translate`, the `Translate`(before TranslateByte) and `TranslateAll`(after TranslateByte) are correct working, but `TranslateByte` is a non-exist command.
https://github.com/yanganto/nvim-translate/blob/develop/rplugin/python/translate.py#L44
If you are willing to point out the exact problem, I will very much appreciate.

**Comment by Shougo** [comment]
https://github.com/yanganto/nvim-translate/blob/develop/rplugin/python/translate.py#L126

It is syntax error.

It must be:

```python
h = s.split('u')[0]
if h:
```

**Comment by Shougo** [comment]
I can see the syntax error by `:UpdateRemotePlugins` output.

**Comment by bfredl** [comment]
@Shougo That is valid syntax in python 3.8, probably unrelated to the actual issue here.

**Comment by Shougo** [comment]
No.  Because the plugin is for Python2.
Please see the rplugin path.

**Comment by bfredl** [comment]
They probably intended it to be for python3, so the file should to be moved to `rplugin/python3` then.

**Comment by yanganto** [comment]
Yep, I use python 3.8.2 on Archlinux, in which default python is Python 3.8.2 now.

**Comment by yanganto** [comment]
I find the command register in ~/.local/share/nvim/rplugin.vim, and everything works well after I use `:UpdateRemotePlugins`, to update the command register.  Thanks for your time.  I am appreciate.
