### ISSUE TITLE
Error command aarch64-linux-android-gcc

### ISSUE THREAD

**Issue by Robin1451** [neovim/pynvim#444]
Facing this issue while installing pyaudio

**Comment by Shougo** [comment]
I don't understand.
You should explain the problem more clearly.

**Comment by Robin1451** [comment]
![Screenshot_20200503-000117](https://user-images.githubusercontent.com/64700782/80916787-8f6b7e80-8d78-11ea-985c-50aa9b1d76e1.png)

**Comment by Robin1451** [comment]
This is the error I'm facing while installing pyaudio on android device

**Comment by Robin1451** [comment]
This is the error when I try to install pyaudio. I'm running python on
android device, using Qpython app. I've also tried on pydroid 3. I also
tried installing port audio.

**Comment by Shougo** [comment]
This is *not* pynvim's issue.
It is just *pyaudio* does not support your platform.

**Comment by Robin1451** [comment]
Are there any alternatives available for pyaudio

**Comment by Shougo** [comment]
I don't know...
