### ISSUE TITLE
How to clear output (vim.out_write)

### ISSUE THREAD

**Issue by pianocomposer321** [neovim/pynvim#446]
After getting input from neovim with self.vim.eval('input("Enter a value: ")'), if I echo the output with either self.vim.out_write or self.vim.command("echo"), it doesn't clear "Enter a value: " before echo-ing.

Example:
![image](https://user-images.githubusercontent.com/54072354/81441126-d2da3a00-9136-11ea-8ebd-66b4e17b0df4.png)

**Comment by Shougo** [comment]
`self.vim.command("redraw | echo")` fixes your issue.

**Comment by pianocomposer321** [comment]
Thanks @Shougo! Closing the issue now.
