### ISSUE TITLE
:echo has("python3") returns "0" even though i have pynvim installed

### ISSUE THREAD

**Issue by Rentfunk** [neovim/pynvim#448]
I have installed pynvim as per instructions at https://github.com/Shougo/deoplete.nvim but it's not working in my vim. And i tried everything. Installing neovim. Then uninstalling both and installing only pynvim, but nothing happens. Can you help me with this?

**Comment by Shougo** [comment]
Please upload `:checkhealth` result.

**Comment by Rentfunk** [comment]
Well, `:checkhealth` command is not working in my vim. 
And this is what my `pip3 freeze` returns:
asgiref==3.2.5 
certifi==2019.11.28
Django==3.0.4
django-filter==2.2.0
greenlet==0.4.16
msgpack==1.0.0
neovim==0.3.1
pynvim==0.4.1
python-decouple==3.3
pytz==2019.3
sqlparse==0.3.1
