### ISSUE TITLE
Use absolute imports

### ISSUE THREAD

**Issue by farisachugthai** [neovim/pynvim#450]
Throughout the repository, relative imports are used.

As a result, simple and useful checks for the repository are missed.

For example:

`python3 -m doctest api/nvim.py`

Can't work because the internal imports are relative; however, if all the imports were refactored from

```python3

from .buffer import Buffer

# to

from pynvim.buffer import Buffer

```

simple checks like this would be possible.

**Comment by Shougo** [comment]
Can you send the PR for it?

**Comment by farisachugthai** [comment]
Would you want me to change all of the imports throughout the entire repository or focus on certain files?

The diff will be large if I change the repository; however, I see absolutely no downside to doing so.

Either way I'd love to send a PR! Just let me know what you're thinking.

**Comment by Shougo** [comment]
I also think absolute imports are better.

**Comment by farisachugthai** [comment]
I'm glad you agree. Are there any concerns that would stop

<https://github.com/neovim/pynvim/pull/451> 

from being merged?

**Comment by Shougo** [comment]
Other reviwers eye are needed.
