### ISSUE TITLE
Failed to load python3 host

### ISSUE THREAD

**Issue by LifeOfJona** [neovim/pynvim#475]
This was working perfectly fine before I believe. Not quite sure what the error might be?

![image](https://user-images.githubusercontent.com/44353899/104359848-30046780-54de-11eb-8a59-6a18b1788e0e.png)

I've done the following:
- Run in shell: pip3 install pynvim

Which gives me back the following:
```
Requirement already satisfied: pynvim in /usr/local/lib/python3.9/site-packages (0.4.2)
Requirement already satisfied: greenlet in /usr/local/lib/python3.9/site-packages (from pynvim) (0.4.17)
Requirement already satisfied: msgpack>=0.5.0 in /usr/local/lib/python3.9/site-packages (from pynvim) (1.0.2)
```

Appreciate the help.

**Comment by Shougo** [comment]
You should check the path.
neovim Python is under /usr/.
But your pip is under /usr/local.

**Comment by LifeOfJona** [comment]
> You should check the path.
> neovim Python is under /usr/.
> But your pip is under /usr/local.

I'm sorry, I've literally checked everywhere I can think of and I'm unable to find it. 

It does indicate it's satisfied at: pynvim in /usr/local/lib/python3.9/site-packages/pynvim but I'm confused as what path I should be providing to Neovim as that's just a path leading to the directory and not the application itself.

Thanks.

**Comment by Shougo** [comment]
You need to install pynvim under /usr     python3 or you need to change change neovim python path to /usr/local by g:python3_host_prog.

**Comment by LifeOfJona** [comment]
Hey, there was a difference in the Python versions that were being used and Pip was pointing to a different Python version than Pynvim was using. 

Thanks.
