### ISSUE TITLE
[QUESTION] How to create buffer with pynvim?

### ISSUE THREAD

**Issue by peach-lasagna** [neovim/pynvim#479]
i want to do something like this:
![изображение](https://user-images.githubusercontent.com/59787538/110447072-70edb680-80f2-11eb-8bc0-4e56716df4b5.png)
(this is vim plug)

**Comment by peach-lasagna** [comment]
nvim_win_set_config

**Comment by bfredl** [comment]
call api functions like `nvim.api.create_buffer(True, True)`  and `win.api.set_config` (where win is a window object).
