### ISSUE TITLE
ImportError: dlopen(venv/lib/python3.9/site-packages/gevent/_gevent_c_hub_local.cpython-39-darwin.so, 2): no suitable image found

### ISSUE THREAD

**Issue by jiaxin-hou** [neovim/pynvim#507]
ImportError: dlopen(/venv/lib/python3.9/site-packages/gevent/_gevent_c_hub_local.cpython-39-darwin.so, 2): no suitable image found.  Did find:
	/venv/lib/python3.9/site-packages/gevent/_gevent_c_hub_local.cpython-39-darwin.so: mach-o, but wrong architecture
	/venv/lib/python3.9/site-packages/gevent/_gevent_c_hub_local.cpython-39-darwin.so: mach-o, but wrong architecture

**Comment by justinmk** [comment]
report it to gevent, not pynvim
