### ISSUE TITLE
[request] Update pypi release

### ISSUE THREAD

**Issue by yozachar** [neovim/pynvim#514]
It's been over a year. Please create a new tagged release for [PyPi](https://pypi.org/project/pynvim/).

**Comment by wookayin** [comment]
+1. Looking forward to #496 being merged.

**Comment by stsewd** [comment]
Anything we can do to help with the new release? I found this bug https://github.com/neovim/pynvim/pull/496 and realized it was already fixed in master :D

**Comment by wookayin** [comment]
/cc @justinmk 

Please neovim maintainers have more attention to this repo as well as neovim-core.

**Comment by clason** [comment]
> It's been over a year. Please create a new tagged release for [PyPi](https://pypi.org/project/pynvim/).

1. there hasn't been any significant changes since the last release, so tagging a new one now would just be release theatre

> Please neovim maintainers have more attention to this repo as well as neovim-core.

2. that's not how this work; time is a finite resource, especially for volunteer work, which is understandably focused on core work (especially since the constantly improving Lua API makes Python plugins less and less popular).

**Comment by clason** [comment]
> Anything we can do to help with the new release? I found this bug https://github.com/neovim/pynvim/pull/496 and realized it was already fixed in master :D

Help is welcome. The first step would be to review https://github.com/neovim/pynvim/pull/519 and make sure it works, or improve so it passes current requirements.

**Comment by joe733** [comment]
#496 and #519 are merged.

**Comment by justinmk** [comment]
Released 0.5: https://github.com/neovim/pynvim/releases/tag/0.5.0

**Comment by wookayin** [comment]
Hmm I wish I had some discussion and set the scope before we cut the 0.5 release...

**Comment by justinmk** [comment]
@wookayin we can always do another followup release
