### ISSUE TITLE
After updated to python 3.11,   neovim can't find pynvim  even I already install pynvim 

### ISSUE THREAD

**Issue by ancion** [neovim/pynvim#516]
========================================================================
  - INFO: Platform: win
  - INFO: Nvim Version: NVIM v0.8.0-1210-gd367ed9b2
  
nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

========================================================================
## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "F:\Scoop\apps\python\current\python.exe"
  - INFO: Executable: F:\Scoop\apps\python\current\python.exe
  - ERROR: Command error (job=17, exit code 1): `"F:\Scoop\apps\python\current\python.exe" -c "import sys; sys.path = [p for p in sys.path if p != """"]; import neovim; print(neovim.__file__)"` (in 'C:\Users\unicorn')
    stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "F:\Scoop\apps\python\current\Lib\site-packages\neovim\__init__.py", line 5, in <module>
    import pynvim
  File "F:\Scoop\apps\python\current\Lib\site-packages\pynvim\__init__.py", line 11, in <module>
    from pynvim.msgpack_rpc import (ErrorResponse, child_session, socket_session,
  File "F:\Scoop\apps\python\current\Lib\site-packages\pynvim\msgpack_rpc\__init__.py", line 10, in <module>
    from pynvim.msgpack_rpc.session import ErrorResponse, Session
  File "F:\Scoop\apps\python\current\Lib\site-packages\pynvim\msgpack_rpc\session.py", line 7, in <module>
    import greenlet
  File "F:\Scoop\apps\python\current\Lib\site-packages\greenlet\__init__.py", line 29, in <module>
    from ._greenlet import _C_API # pylint:disable=no-name-in-module
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'greenlet._greenlet'
  - INFO: Python version: 3.11.0
  - INFO: pynvim version: unable to load neovim Python module
  - ERROR: pynvim is not installed.
    Error: unable to load neovim Python module
    - ADVICE:
      - Run in shell: F:\Scoop\apps\python\current\python.exe -m pip install pynvim
  - WARNING: Could not contact PyPI to get latest version.
  - ERROR: HTTP request failed: error: curl error with https://pypi.python.org/pypi/pynvim/json: 56

========================================================================================

## What I tried
-  `python -m pip install pynvim`   command can't fix this
- following is output
```
 ﬘ —— python -m pip install pynvim
Requirement already satisfied: pynvim in f:\scoop\apps\python\current\lib\site-packages (0.4.3)
Requirement already satisfied: msgpack>=0.5.0 in f:\scoop\apps\python\current\lib\site-packages (from pynvim) (1.0.3)
Requirement already satisfied: greenlet in f:\scoop\apps\python\current\lib\site-packages (from pynvim) (1.1.2)
  unicorn   ~ 
 ﬘ ——
```

**Comment by wookayin** [comment]
Try: `python -m install -I --upgrade greenlet`

**Comment by ancion** [comment]
thank you, but which prompt `No module named install` 

following command worked ！ 😂

```shell
python -m pip install --upgrade  greenlet
```
