### ISSUE TITLE
pynvim needs to be updated to use pyproject.toml

### ISSUE THREAD

**Issue by badboy1cdx** [neovim/pynvim#518]
When I just recently installed pynvim, I was presented with a deprecation warning that stated that starting in pip ver 23.1, pip will require compliance with using a pyproject.toml file for module installation, instead of the legacy setup.py file that pynvim currently uses.  Therefore I would recommend updating the package and migrating to a pyproject.toml file for setup as soon as possible to avoid having installation broken when pip starts forcing compliance.

**Comment by justinmk** [comment]
any chance you could send a PR?

**Comment by badboy1cdx** [comment]
I was actually considering doing just that.  I've just never worked with packaging before so I figured this would be a good learning opportunity.  I'll send the PR once I get it done.  I estimate two weeks due to current time constraints.

**Comment by zachliu** [comment]
just saw the same msg today
```
DEPRECATION: pynvim is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
```
@badboy1cdx thank you in advance!

**Comment by orenteriab** [comment]
Bump on this as today I got this message:
```
Collecting pynvim
  Using cached pynvim-0.4.3.tar.gz (56 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
      [end of output]
```

**Comment by badboy1cdx** [comment]
PR has been submitted.  See: #519
