### ISSUE TITLE
Can't install pynvim with pipx

### ISSUE THREAD

**Issue by joe733** [neovim/pynvim#522]
```console
$ pipx install pynvim                                                           

No apps associated with package pynvim or its dependencies. If you are attempting to install a library, pipx should not be used. Consider using pip
or a similar tool instead.
```

related: #514

**Comment by badboy1cdx** [comment]
As I understand it, pipx only works for applications that have cli entrypoints.  As pynvim is purely a library and not an application with cli functionality it specifically will not work with pipx.  See the following link for pipx vs pip comparison:

[Comparison to Other Tools - pipx](https://pypa.github.io/pipx/comparisons/)

In  short, I don't believe this is an issue.
