### ISSUE TITLE
pin install pynvim fails to build greenlet on windows

### ISSUE THREAD

**Issue by benfranklin79** [neovim/pynvim#525]
I have python installed on windows using pyenv-win at version 3.12.0a7.
I've also installed the C++ build tools. 
When I first ran the following command:

```
pip3 install pynvim
```

I got errors suggested that I should install the wheel package so I did using the command `pip3 install wheel`. That installed successfully then I ran the above pynvim install command again and got the following output:

https://gist.github.com/benfranklin79/7b832381b67c74d66a273cd3b9f3a6bb

**Comment by justinmk** [comment]
duplicate https://github.com/neovim/pynvim/issues/512
