### ISSUE TITLE
How do you access the treesitter API via pynvim?

### ISSUE THREAD

**Issue by kdog3682** [neovim/pynvim#568]
When I inspect nvim.api.treesitter , I get a "class functions.partial".

However, when I tried to do nvim.api.treesitter.get_node(). I get the message that get_node is not defined.

Really ppreciate any advice on how to use pynvim API for this.

**Comment by justinmk** [comment]
via Lua https://pynvim.readthedocs.io/en/latest/usage/python-plugin-api.html#lua-integration
