### ISSUE TITLE
Publish version 0.5.1

### ISSUE THREAD

**Issue by svermeulen** [neovim/pynvim#577]
There are some subtle bugs that currently completely break remote python plugins for some users on windows, and which are fixed in the preview version, but not in the published 0.5.0 version.  In particular, [this bug](https://github.com/neovim/pynvim/issues/564).  I find myself recommending people install directly from git url instead often and see people lose a lot of time to this.  Is there a reason 0.5.1 still isn't published?

**Comment by wookayin** [comment]
Completed in #580. https://pypi.org/project/pynvim/0.5.1/

**Comment by kiyoon** [comment]
This version is broken because of the lack of `typing_extensions` as I mentioned in #582. Shouldn't it be hot-fixed asap as it's a fatal bug?

**Comment by jamessan** [comment]
@kiyoon Is this what #581 fixed?

**Comment by kiyoon** [comment]
@jamessan that also fixed a similar issue but if you open the 0.5.1 version, there is no `typing_extensions` at all! So there must be another commit that fixed it

**Comment by jamessan** [comment]
If I build a wheel from the current master, then I see typing_extensions showing up:

```
Requires-Dist: typing-extensions >=4.5 ; python_version < "3.12"
```

so that should be good, right?

**Comment by kiyoon** [comment]
@jamessan that looks good to me, and from what @wookayin confirmed in https://github.com/neovim/pynvim/issues/582#issuecomment-2470708148, it should have been fixed by #581

**Comment by kiyoon** [comment]
Once the next version is released, I suggest **yanking** the broken version on PyPI. This way, it won't let users to accidentally install the version, but it is still available to download if users specifically asks for the version.

**Comment by jamessan** [comment]
> Now that the new version is released, I suggest yanking the broken version on PyPI.

I don't have access to do that. I think @bfredl or @justinmk would need to do that, if we wanted to.

**Comment by bfredl** [comment]
@jamessan congratulations, you are now a co-owner of the project
