### ISSUE TITLE
typing_extensions should be a dependency

### ISSUE THREAD

**Issue by kiyoon** [neovim/pynvim#582]
Fresh-installing pynvim on a new environment will fail to import the module due to the lack of `typing_extensions` (at least in Python 3.9). Thus the package should be listed as a dependency, maybe depending on the python version.

**Comment by kiyoon** [comment]
I think it's already addressed in the master branch, but maybe not the pypi version 0.5.1. Sorry! Closing as completed

**Comment by wookayin** [comment]
While I can see that this has been fixed in #581, but I don't see why [CI](https://github.com/neovim/pynvim/blob/master/.github/workflows/test.yml) hadn't been unable to catch this (before #581 was merged).

**Comment by kiyoon** [comment]
@wookayin ahh that makes sense. Very interesting bug! Thanks for investigating :))
